// Regenerates src/config/topics-dates.ts: the last-modified date of every
// game topic, taken from `git blame` over the topic's entry in
// src/config/topics-data.ts and its FAQ in src/config/topics-faq.ts.
// The date feeds the sitemap <lastmod> and the "Updated" line on the page.
//
// Needs full git history (run `git fetch --unshallow` in a shallow clone).
// Usage: node scripts/topic-dates.mjs
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const DATA = 'src/config/topics-data.ts';
const FAQ = 'src/config/topics-faq.ts';
const OUT = 'src/config/topics-dates.ts';

/** Author date (YYYY-MM-DD, author's own time zone) for each line of a file. */
function blameDates(file) {
  const out = execFileSync('git', ['blame', '--line-porcelain', file], {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  });
  const dates = [];
  let time = 0;
  let tz = '+0000';
  for (const line of out.split('\n')) {
    if (line.startsWith('author-time ')) time = Number(line.slice(12));
    else if (line.startsWith('author-tz ')) tz = line.slice(10);
    else if (line.startsWith('\t')) {
      const sign = tz[0] === '-' ? -1 : 1;
      const offset =
        sign * (Number(tz.slice(1, 3)) * 60 + Number(tz.slice(3, 5)));
      dates.push(
        new Date((time + offset * 60) * 1000).toISOString().slice(0, 10)
      );
    }
  }
  return dates;
}

/** Latest blame date per slug, for entries whose first line matches `start`. */
function latestBySlug(file, start, into) {
  const lines = execFileSync('git', ['show', `HEAD:${file}`], {
    encoding: 'utf8',
  }).split('\n');
  const dates = blameDates(file);
  let slug = null;
  for (let i = 0; i < lines.length; i++) {
    const found = start(lines, i);
    if (found) slug = found;
    // A closing `];` / `};` ends the current list — helper code between
    // arrays must not count towards the last topic.
    else if (/^[\]}];?$/.test(lines[i])) slug = null;
    if (slug && dates[i] && (!into[slug] || dates[i] > into[slug])) {
      into[slug] = dates[i];
    }
  }
}

const result = {};
// Topic entries: `  t(` / `  g(` followed by `    '<slug>',`.
latestBySlug(
  DATA,
  (lines, i) =>
    /^ {2}[tg]\($/.test(lines[i]) &&
    /^ {4}'([a-z0-9-]+)',$/.exec(lines[i + 1] ?? '')?.[1],
  result
);
// FAQ entries: `  '<slug>': [`.
latestBySlug(
  FAQ,
  (lines, i) => /^ {2}'([a-z0-9-]+)': \[$/.exec(lines[i])?.[1],
  result
);

const body = Object.keys(result)
  .sort()
  .map((slug) => `  '${slug}': '${result[slug]}',`)
  .join('\n');

writeFileSync(
  OUT,
  `// Generated by scripts/topic-dates.mjs — last-modified date per topic slug.\n` +
    `// Re-run after editing topics-data.ts or topics-faq.ts (needs full git history).\n` +
    `export const TOPIC_UPDATED: Record<string, string> = {\n${body}\n};\n`
);
console.log(`${Object.keys(result).length} topic dates written to ${OUT}`);
